spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  messages:
    encoding: UTF-8
    basename: classpath:i18n/messages
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    aws:
      region:
        static: ${REGION}
      credentials:
        accessKey: ${ACCESS_KEY_AWS}
        secretKey: ${SECRET_KEY_AWS}
  s3:
    bucket-name: ${BUCKET_NAME}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs

hazelcast:
  dkmicroservices:
    address: localhost:5701
    cluster_name: dev

rate-limit:
  limit: 2
  seconds: 60

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

security:
  auth:
    login-url: /api/v1/auth/login
    header-name: Authorization
    header-prefix: "Bearer "
    secret-key: foobar_123456789_foobar_123456789_foobar_123456789_foobar_123456789

grpc:
  client:
    grpc-department-service:
      host: localhost
      port: 8010
      address: static://localhost:8010
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    grpc-employee-service:
      host: localhost
      port: 8020
      address: static://localhost:8020
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    grpc-auth-service:
      host: localhost
      port: 8040
      address: static://localhost:8040
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    grpc-notification-service:
      host: localhost
      port: 8050
      address: static://localhost:8050
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    grpc-location-service:
      host: localhost
      port: 8060
      address: static://localhost:8060
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    grpc-tracking-service:
      host: localhost
      port: 8070
      address: static://localhost:8070
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    grpc-recruitment-service:
      host: localhost
      port: 8080
      address: static://localhost:8080
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    grpc-attendance-service:
      host: localhost
      port: 8090
      address: static://localhost:8090
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    grpc-payroll-service:
      host: localhost
      port: 8110
      address: static://localhost:8110
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

server:
  port: 8003
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints: # Actuator Prometheus Endpoint
    web:
      exposure:
        include: prometheus