spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payroll_db?createDatabaseIfNotExist=true&useEncoding=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
    username: ngdangkiet
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8101

grpc:
  server:
    port: 8110
  client:
    grpc-employee-service:
      host: employee-service
      port: 8020
      address: static://employee-service:8020
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    grpc-attendance-service:
      host: attendance-service
      port: 8090
      address: static://attendance-service:8090
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    hostname: payroll-service
    prefer-ip-address: true
    non-secure-port: ${grpc.server.port}

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints: # Actuator Prometheus Endpoint
    web:
      exposure:
        include: prometheus