spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://tracking-elasticsearch:9200

server:
  port: 8007

grpc:
  server:
    port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    hostname: tracking-service
    prefer-ip-address: true
    non-secure-port: ${grpc.server.port}

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints: # Actuator Prometheus Endpoint
    web:
      exposure:
        include: prometheus